@@startuml
hide circle
skinparam linetype ortho

entity "SAIFU" as saifu {
}

entity "SAIFUカテゴリー" as saifuCategory {
}

entity "SAIFU履歴" as saifuHistory {
}

entity "収入" as income {
}

entity "収入明細" as incomeDetail {
}

entity "収入メインカテゴリ" as incomeCategoryMain {
}

entity "収入サブカテゴリ" as incomeCategorySub {
}

entity "給与控除" as salaryDeduction {
}

entity "給与控除明細" as salaryDeductionDetail {
}

entity "投資" as investment {
}

entity "投資明細" as investment {
}

entity "投資商品" as investmentItem {
}

entity "投資商品履歴" as investmentItemHistory {
}

entity "投資商品メインカテゴリ" as investmentItemCategoryMain {
}

entity "投資商品サブカテゴリ" as investmentItemCategorySub {
}

entity "支出" as expense {
}

entity "支出明細" as expenseDetail {
}

entity "支出メインカテゴリ" as expenseMainCategory {
}

entity "支出サブカテゴリ" as expenseSubCategory {
}

entity "負債" as debt {
}

entity "負債明細" as debtDetail {
}

entity "負債アイテム" as debtItem {
}

entity "負債アイテム履歴" as debtItemHistory {
}

entity "負債メインカテゴリ" as debtMainCategory {
}

entity "負債サブカテゴリ" as debtSubCategory {
}

entity "テナント" as tenant {
}

entity "ユーザー" as user {
}

entity "システム設定" as systemSettings {
}

@@enduml