
@startuml ER_Concept
skinparam linetype ortho

' Entity
entity "m_tenants" as tenant{
  ** id : UUID <<generated>> **
  --
  name : VARCHAR(10)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_roles" as role {
  ** id : UUID <<generated>> **
  --
  name : VARCHAR(10)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_users" as user {
  ** id : UUID <<generated>> **
  --
  tenant_id : UUID <<FK>>
  role_id : UUID <<FK>>
  --
  login_id : VARCHAR(100)
  name: VARCHAR(30)
  password : VARCHAR(30)
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_saifu_main_categories" as saifuCategoryMain {
  ** id : SERIAL <<generated>> **
  --
  tenant_id <FK>
  --
  name : VARCHAR(20)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_saifu_sub_categories" as saifuCategorySub {
  ** id : SERIAL <<generated>> **
  --
  saifu_main_category_id : INTEGER <FK>
  tenant_id : UUID <<FK>
  --
  name : VARCHAR(30)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_saifu" as saifu {
  ** id : UUID <<generated>> **
  --
  user_id : UUID <<FK>>
  saifu_sub_category_id : INTEGER <<FK>>
  --
  name : VARCHAR(20)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_saifu_transfers" as saifuTransfer {
  ** id : UUID <<generated>> **
  --
  from_saifu_id : UUID <<FK>>
  to_saifu_id : UUID <<FK>>
  --
  amount : BIGINT
  comment : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_income_main_categories" as incomeCategoryMain {
  ** id : SERIAL <<generated>> **
  --
  tenant_id : UUID <<FK>>
  --
  name : VARCHAR(20)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_income_sub_categories" as incomeCategorySub {
  ** id : SERIAL <<generated>> **
  --
  income_main_category_id : INTEGER <<FK>>
  tenant_id : UUID <<FK>
  --
  name : VARCHAR(20)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_income" as income {
  ** transaction_id : UUID <<generated>> **
  --
  user_id : UUID <<FK>>
  --
  total : BIGINT
  comment : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_income_details" as incomeDetail {
  ** id : UUID <<generated>> **
  --
  income_transaction_id : UUID <<FK>>
  income_sub_category_id : INTEGER <FK>
  --
  amount : BIGINT
  memo : VARCHAR(100)
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_expense_main_categories" as expenseCategoryMain {
  ** id : SERIAL <<generated>> **
  --
  tenant_id : UUID <<FK>
  --
  name : VARCHAR(20)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_expense_sub_categories" as expenseCategorySub {
  ** id : SERIAL <<generated>> **
  --
  expense_category_main_id : INTEGER <<FK>>
  tenant_id : UUID <<FK>
  --
  name : VARCHAR(30)
  explain : TEXT
  deduction_flag : BOOLEAN
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_expense" as expense {
  ** id : UUID <<generated>> **
  --
  user_id : UUID <<FK>>
  deduction_income_transaction_id : UUID <<FK>>
  --
  total : BIGINT
  comment : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_expense_details" as expenseDetail {
  ** id : UUID <<generated>> **
  --
  expense_id : UUID <<FK>>
  expense_sub_category_id : INTEGER <<FK>>
  --
  amount : BIGINT
  memo : VARCHAR(100)
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_investment_item_main_categories" as investmentItemCategoryMain {
  ** id : SERIAL <PK> **
  --
  tenant_id : UUID <<FK>>
  --
  name : VARCHAR(20)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_investment_item_sub_categories" as investmentItemCategorySub {
  ** id : SERIAL <<generated>> **
  --
  investment_category_main_id : INTEGER <<FK>>
  tenant_id : UUID <<FK>
  --
  name : VARCHAR(30)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_investment_items" as investmentItem {
  ** id : UUID <<generated>> **
  --
  user_id : UUID <<FK>>
  investment_item_sub_category_id : INTEGER <<FK>>
  --
  name : VARCHAR(50)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_investments" as investment {
  ** transaction_id : UUID <<generated>> **
  --
  user_id : UUID <<FK>>
  related_income_transaction_id : UUID <<FK>>
  --
  total : BIGINT
  comment : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_investment_details" as investmentDetail {
  ** id : UUID <<generated>> **
  --
  investmemt_transaction_id : UUID <<FK>>
  investment_item_id : UUID <<FK>>
  --
  amount : BIGINT
  comment: TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_investment_item_histories" as investmentItemHistory {
  ** id : UUID <<generated>> **
  --
  investment_detail_id : UUID <<FK>>
  investment_item_id : UUID <<FK>>
  --
  income : BIGINT
  outcome : BIGINT
  balance : BIGINT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_debt_main_categories" as debtCategoryMain {
  ** id : SERIAL <<generated>> **
  --
  tenant_id : UUID <<FK>>
  --
  name : VARCHAR(20)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_debt_sub_categories" as debtCategorySub {
  ** id : SERIAL <PK> **
  --
  debt_category__main_id : INTEGER <FK>
  tenant_id : UUID <<FK>
  --
  name : VARCHAR(30)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "m_debt_items" as debtItem {
  ** id : UUID <<generated>> **
  --
  user_id : UUID <<FK>>
  debt_sub_category_id <<FK>>
  --
  debt_item_name : VARCHAR(30)
  explain : TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_debt" as debt {
  ** id : UUID <<generated>> **
  --
  user_id : UUID <<FK>>
  related_income_transaction_id : UUID <<FK>>
  --
  total : BIGINT
  comment: TEXT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_debt_details" as debtDetail {
  ** id : UUID <<generated>> **
  --
  debt_id : UUID <<FK>>
  debt_item_id : UUID <<FK>>
  --
  amount : BIGINT
  memo : VARCHAR(100)
  created : DATETIME
  updated : DATETIME
}

entity "t_debt_item_histories" as debtItemHistory {
  ** id : UUID <<generated>> **
  --
  debt_detail_id : UUID <<FK>>
  debt_item_id : UUID <<FK>>
  --
  borrowing : BIGINT
  repayment : BIGINT
  balance : BIGINT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

entity "t_saifu_histories" as saifuHistory {
  ** id : UUID <<generated>> **
  --
  saifu_id : UUID <<FK>>
  income_transaction_id : UUID <<FK>>
  expense_transaction_id : UUID <<FK>>
  investment_transaction_id: UUID <<FK>>
  debt_transaction_id: UUID <<FK>>
  safu_transfer_transaction_id : UUID <<FK>>
  --
  income : BIGINT
  outcome : BIGINT
  balance : BIGINT
  delete_flag : BOOLEAN
  created : DATETIME
  updated : DATETIME
}

' Relation

' Account
tenant ||..o{user
role ||..o{user

' SAIFU
user ||..|{saifu
saifu ||..|{saifuHistory
tenant ||..|{saifuCategoryMain
saifuCategoryMain ||..|{saifuCategorySub
saifuCategorySub ||..o{saifu
saifu ||..o{saifuTransfer
saifuTransfer ||..|| saifuHistory

' Income
tenant ||..|{incomeCategoryMain
incomeCategoryMain ||..|{incomeCategorySub
incomeCategorySub ||..o{incomeDetail
user ||..o{income
income ||..|{incomeDetail
income ||..||saifuHistory
income ||..o|investment
income ||..o|expense
income ||..o|debt

' Expense
tenant ||..|{expenseCategoryMain
expenseCategoryMain ||..|{expenseCategorySub
expenseCategorySub ||..o{expenseDetail
user ||..o{expense
expense ||..|{expenseDetail
expense ||..o|saifuHistory

' Investment
tenant ||..|{investmentItemCategoryMain
investmentItemCategoryMain ||..|{investmentItemCategorySub
investmentItemCategorySub ||..o{investmentItem
user ||..O{investment
investment ||..|{investmentDetail
investment ||..o|saifuHistory
investmentDetail ||..||investmentItemHistory
investmentItem ||..|{investmentItemHistory
investmentItem ||..o{investmentDetail
user ||..o{investmentItem

' Debt
tenant ||..|{debtCategoryMain
debtCategoryMain ||..|{debtCategorySub
debtCategorySub ||..o{debtItem
user ||..{debt
debt ||..|{debtDetail
debt ||..o|saifuHistory
debtDetail ||..||debtItemHistory
debtItem ||..o{debtDetail
debtItem ||..|{debtItemHistory
user ||..o{debtItem

@enduml